
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ProjectType = {
  LANDING_PAGE: 'LANDING_PAGE',
  WEB_APP: 'WEB_APP',
  MOBILE_APP: 'MOBILE_APP',
  E_COMMERCE: 'E_COMMERCE',
  CMS: 'CMS',
  SAAS: 'SAAS',
  PORTFOLIO: 'PORTFOLIO',
  BLOG: 'BLOG',
  DASHBOARD: 'DASHBOARD',
  MARKETPLACE: 'MARKETPLACE',
  GAME: 'GAME',
  CORPORATE_WEBSITE: 'CORPORATE_WEBSITE',
  EDUCATIONAL: 'EDUCATIONAL',
  SOCIAL_NETWORK: 'SOCIAL_NETWORK',
  STREAMING: 'STREAMING',
  FINTECH: 'FINTECH',
  HEALTHCARE: 'HEALTHCARE',
  GOVERNMENT: 'GOVERNMENT',
  AI_TOOL: 'AI_TOOL',
  IOT_APP: 'IOT_APP',
  OTHER: 'OTHER'
} as const

export type ProjectType = (typeof ProjectType)[keyof typeof ProjectType]


export const TaskStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FIRED: 'FIRED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const ProjectStatus = {
  IN_DEVELOPMENT: 'IN_DEVELOPMENT',
  COMPLETED: 'COMPLETED',
  PAUSED: 'PAUSED',
  CANCELED: 'CANCELED'
} as const

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus]
